### ISSUE TITLE
I hava see you pull a request to vim ,what do you think about neovim ?

### ISSUE THREAD

**Issue by wsdjeg** [marshallward/TiledSharp#19]
I hava tried with neovim ,but I cannot find the different between them .

**Comment by marshallward** [comment]
I don't know very much about neovim, sorry.  I know that it is a rewrite, and that most of its benefits would be for contributors and plugin developers, rather than users.

This is not a TiledSharp issue, so I am closing this ticket.

**Comment by wsdjeg** [comment]
ok thank you very much
