### ISSUE TITLE
Collision Editor Support

### ISSUE THREAD

**Issue by diegomachado** [marshallward/TiledSharp#20]
Hey guys,

Do you have any plans to implement an abstraction layer for Collision Editor, just like we have for AnimationFrames?

I'd like to develop that, but I got some issues trying to compile it on my Mac, and I'm not that confident to keep the project conventions.

And correct me if I'm wrong, but in the current state I can get them via Tileset.Tile.ObjectGroups, right?
Thanks!

**Comment by diegomachado** [comment]
Just tested it and if I try to define any Tile collision, I get the following error:

```ArgumentNullException: Argument cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[System.String,TiledSharp.TmxObjectGroup].ContainsKey (System.String key) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.Generic/Dictionary.cs:458)
System.Collections.ObjectModel.KeyedCollection`2[System.String,TiledSharp.TmxObjectGroup].Contains (System.String key) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Collections.ObjectModel/KeyedCollection.cs:75)
TiledSharp.TmxList`1[TiledSharp.TmxObjectGroup].Add (TiledSharp.TmxObjectGroup t)
TiledSharp.TmxTilesetTile..ctor (System.Xml.Linq.XElement xTile, TiledSharp.TmxList`1 Terrains, System.String tmxDir)
TiledSharp.TmxTileset..ctor (System.Xml.Linq.XElement xTileset, System.String tmxDir)
TiledSharp.TmxMap..ctor (System.String filename)```

I'm using Tiled 0.14.2

**Comment by marshallward** [comment]
Yes, it looks like collisions are just stored as objectgroups within each tile, which is supported, but it looks like some variable needs to be set as nullable.

I'll have a look right now and see if I can reproduce the problem.  If not, then you might need to attach the TMX file.

**Comment by marshallward** [comment]
I don't get any runtime errors from parsing the file containing collision data.

I can access the information, but it is not very intuitive.  The tileset tiles are saved as lists, rather than dictionaries (or the hybrid TmxList type), so the first tile in the TMX file must be accessed as map.Tilesets[i].Tiles[0], rather than its Tile ID.

I am not seeing any `ArgumentNullException` errors, so I think your problem may be different. 

How are you accessing the collision data in your C# source?

**Comment by marshallward** [comment]
BTW this is how I accessed my object group:

    TmxMap map;
    var x = map.Tilesets[0].Tiles[0].Objectgroups[0].Object[0].X

**Comment by diegomachado** [comment]
All right @marshallward, I got it solved. 
I was using this: https://github.com/bradur/TiledSharp/releases/tag/Unity

It's a DLL from a fork that's probably outdated. Just used the current code from your repo instead of DLL and it's working now.

But, nonetheless, it would be awesome to have an abstraction for Tiled's Collision Editor data. As you said, is not intuitive at all.

Having a class for each type of collider with it's origin, radius (in case of an ellipse) and points would be very helpful.

Thank you very much for TiledSharp and your support here. :grinning: :+1:

**Comment by marshallward** [comment]
Yeah, I made some changes recently to improve Unity compatibility (thanks in part to bradur's work).  I belive that Unity also recently updated its Mono runtime, which may have helped.

I've generally tried to only emulate the TMX representation and not add any additional features; ideally I'd like to see those in render engines using TiledSharp.  But I agree that there's some major issues with accessing the collision data.  I'll take another look at it over the Christmas break.

Thanks for using the software :)
