### ISSUE TITLE
Unhandled exception when loading map that has Image layers

### ISSUE THREAD

**Issue by Zarickan** [marshallward/TiledSharp#23]
"An unhandled exception of type 'System.ArgumentNullException' occurred in System.Xml.Linq.dll
Additional information: Value cannot be null."

Occurs when i try to load a tiled map that has ImageLayers, if I remove the image layer from the map everything loads just fine.

**Part of stacktrace (error occurs on TmxMap ctor):**
   at System.Xml.Linq.XAttribute.op_Explicit(XAttribute attribute)
   at TiledSharp.TmxImageLayer..ctor(XElement xImageLayer, String tmxDir)
   at TiledSharp.TmxMap..ctor(String filename)

**Comment by Zarickan** [comment]
After downloading the source code to use instead of the NuGet package so I could fix the error everything worked.
II guess the NuGet version has to be updated.

**Comment by marshallward** [comment]
Thanks for letting me know.  I didn't realise that anyone was even using that nuget version.

I'm on a work trip this week, but I'll try to get it updated soon.

Thanks again!

**Comment by marshallward** [comment]
I've just updated the NuGet package, hopefully it's working fine.
