### ISSUE TITLE
TMX format support

### ISSUE THREAD

**Issue by beppe9000** [marshallward/TiledSharp#27]
Is this parser on par with the latest version of Tiled?

**Comment by marshallward** [comment]
It ought to work for Tiled v0.15 output, but I could have missed some things.  Are you seeing any issues?

**Comment by beppe9000** [comment]
I was just wondering... I was selecting a library from this page and i  gotten a little confused by the version compatibility thing i was unsure if it was format version or program version. Now I figured it, thanks. I am happily using TiledSharp right now: no problems so far. :+1:
