### ISSUE TITLE
Support for the Tiled Collision Editor

### ISSUE THREAD

**Issue by anchpop** [marshallward/TiledSharp#40]
The Tiled Collision Editor is a relatively new feature in Tiled that allows you to create ObjectGroups that are associated with a GID (aka a tile in a tileset). This way you can edit the collisions for one tile in your tileset, and it will be instantly applied to every one of that tile in the map. You can access it through View > Tile Collision Editor.

In the TMX, it is represented something like:  

     <tileset>  
     
      <image/>  
      
      <tile>  
      
       <objectgroup>  
       
        <object>  
        
         <polygon/>  
         
        </object>  
        
       </objectgroup>  
       
      </tile>  
      
      <tile>  
      
       <objectgroup>  
       
        <object/>  
        
       </objectgroup>  
       
      </tile>  
      
     </tileset>  
     

Any thoughts on getting support for this? I may take a dive into the code to try and get it working tomorrow

**Comment by marshallward** [comment]
I may have already done this, since it looks like Tiles already cointain their own ObjectGroups.  Can you have a look at what's currently in there?

**Comment by anchpop** [comment]
Sorry, you're right. I've attempted to update the [Data Hierarchy](https://github.com/marshallward/TiledSharp/wiki/TiledSharp-Data-Hierarchy) to reflect that. Thanks for your help!
