### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by aloisdeniel** [marshallward/TiledSharp#48]
That would be a lot easier to have a Nuget package for referencing the project!

_And ideally with .NET Standard support. :)_

**Comment by r2d2rigo** [comment]
There is one but hasn't been updated in over a year: https://www.nuget.org/packages/TiledSharp/

Can we get some CI configured for this @marshallward?

**Comment by megabobik** [comment]
@marshallward Could you update Nuget package, please?

**Comment by marshallward** [comment]
I've tagged the current version as 1.0 and updated NuGet.  Would be good to get feedback to see if everything is working ok.  (As mentioned in other issues, I dont actually use NuGet!)

**Comment by marshallward** [comment]
Closing this for now, going to assume it's all ok unless I hear otherwise, in which case please do reopen.
