### ISSUE TITLE
System.FormatException: Input string was not in a correct format

### ISSUE THREAD

**Issue by DelightedCat** [marshallward/TiledSharp#50]
When using both the NuGet Package Manager or referencing the project myself in VS2017, the above exception throws. It seems to occur as soon I construct a TmxMap class. I assume this is pointing to the way I pass the filename string, but I tried all possible alternative ways I knew to format my string. Nothing worked. This is why I think this is an issue.

When running the code from the project and the exception is thrown, it tells me there is an exception on line 54 of the Layer.cs file. After a quick search, it turns out it might have something to do with the way the string is being parsed to an unsigned int.

My Tiled map uses the CSV format, but other formats do not work for me either.

**Comment by marshallward** [comment]
Can you attach an example .tmx (and .tsx) file or snippet that shows this problem?  L54 does handle CSV parsing, although as mentioned you are having issues with other formats.

Also, just to warn you, the NuGet version is very old.  By "referencing the project yourself", do you mean that you have tried it in the GitHub version?

**Comment by DelightedCat** [comment]
Thanks you for your quick reply! When I said I referenced the project myself I meant I have tried the GitHub version indeed. Here's a paste of the TMX's XML: [https://pastebin.com/3LS1aV5f](url) I don't assume anything is wrong with the file, seeing as it's directly generated by Tiled. Here's another paste of my GameLocation class: [https://pastebin.com/27cjK098](url). When using the NuGet version, the exception is thrown on line 21 where I initialize the class.

When using the GitHub project version, the same exception is thrown but the Layer.cs file opens and the diagnostics tell me the following line of code has an exception: `var gid = uint.Parse(s.Trim());`.

Again, thank you for you quick reply and I hope I will be able to proceed using this amazing library soon!

**Comment by marshallward** [comment]
Thanks, I can't do much testing right now due to travel but I will try to have a look at this in a day or two.

**Comment by marshallward** [comment]
Actually just looking at this quickly, it looks like the data is further encapsulated under `chunk` tags.  This is definitely new to me and unsupported.  From the TMX changlog, it looks like a new 1.1 feature.  This is also probably why your other formats would be failing.

I'll have to read up on this and see how it works before trying to implement it.  Given that I haven't looked at this code in a long time, it might take a bit longer than I'd like.  But I'll try to sort something out in a few days.

**Comment by DelightedCat** [comment]
Thank you. I did a quick search myself and I bumped into this: [http://docs.mapeditor.org/en/stable/reference/tmx-changelog/](url) As far as I understand, the issue is caused with infinite maps only, which is the case with my TMX. 

I just used a non-infinite map and it renders just as intended. Thank you for pointing me in the right direction for now! At least I can make some progress on my project now.

**Comment by marshallward** [comment]
No worries, feel free to keep this ticket open, I'll do a review of all the 1.1 changes.

**Comment by Tekadon58** [comment]
I'm experiencing the same problem, would anyone have a solution?

**Comment by marshallward** [comment]
OK, I'll go ahead and merge this.  Thanks for the feedback.

Deep apologies to everyone, but I am functionally unable to maintain this at the moment.  I don't work on Windows machines and my Mono setup has been deeply broken for many years.
