### ISSUE TITLE
global tile ID not zerobased

### ISSUE THREAD

**Issue by movAX13h** [marshallward/TiledSharp#56]
What's the thought behind TmxLayerTile.Gid not matching the ID shown in Tiled?

https://github.com/marshallward/TiledSharp/blob/ea2e2d87af2641cb5edf945d446576f74a9a9016/TiledSharp/src/Layer.cs#L116

In the previous version of TiledSharp I used, this line looked like this:
`Gid = (int)rawGid - 1;`

**Comment by marshallward** [comment]
No idea, but I cannot find any previous version where this line has changed.  In my repos, it has always been this value.  Were you using another person's fork?

But if there's a bug here then it ought to be fixed.

**Comment by marshallward** [comment]
BTW I just opened up an old TMX file with Tiled 1.2.1 and it appeared to have two layers indexed as 1, 2.  Do your layers start indexing at zero?  Also, is this possibly a `firstgid` issue in `tileset`?  Mine is set to 1.

**Comment by movAX13h** [comment]
Hmm... not sure, maybe I put the `-1` there myself. 
I have 5 layers in the TMX file, first layer has id 1.
I'm not using `TmxTileset`, only `TmxLayerTile.Gid`.

Changing to zero-based will break many applications after an update of TiledSharp since the Gid is such a central property.

**Comment by movAX13h** [comment]
I've looked-up the TMX Map Format ... I think you are right. the Gid is not ment to be the tile id directly but is used by the Tileset class which subtracts `first_gid`. I guess that makes sense if a map uses more than one tileset.
