### ISSUE TITLE
DrawOrderType mixup

### ISSUE THREAD

**Issue by Pluige** [marshallward/TiledSharp#59]
The DrawOrderType enum values are mixed up when being read.

You can find the mixup on lines 40 and 41 of the file "ObjectGroup.cs":
```
{"topdown", DrawOrderType.IndexOrder},
{"index", DrawOrderType.TopDown}
```

That should probably be:
```
{"topdown", DrawOrderType.TopDown},
{"index", DrawOrderType.IndexOrder}
```

Also, it's probably slightly better (though maybe more of a personal preference) to place the creation of the dictionary inside the if-clause, so that the dictionary doesn't get made for no reason when there's no draworder specified, making the code sequence as follows:
```
if (drawOrderValue != null) {
	var drawOrderDict = new Dictionary<string, DrawOrderType> {
		{"unknown", DrawOrderType.UnknownOrder},
		{"topdown", DrawOrderType.TopDown},
		{"index", DrawOrderType.IndexOrder}
	};
	DrawOrder = drawOrderDict[drawOrderValue];
}
```

**Comment by marshallward** [comment]
Thanks very much, and so sorry for the long delay, this has been fixed in f29fb71591200093fa159f53094b8b8d7fab1d17
