### ISSUE TITLE
NuGet package version is not up-to-date

### ISSUE THREAD

**Issue by delightedcat** [marshallward/TiledSharp#64]
Hello,

It seems like the NuGet package for TiledSharp is not entirely up-to-date. Things like the constructor for `TmxMap` that takes an `XDocument` is not present in the NuGet version, while it is included in the latest version on GitHub.

This makes it impossible for me to use the NuGet version in favor of compiling the DLL myself, since I need certain new features. I know the package hasn't been up-to-date for a while and it would be great if it was!

**Comment by lucasteles** [comment]
And the nuget version is not in .net standard yet
